### ISSUE TITLE
Couldn't find 'load_default_simulations'.

### ISSUE THREAD

**Issue by qianweihao** [MAGALA-RICHARD/apsimNGpy#16]
![Snipaste_2024-09-20_09-20-30](https://github.com/user-attachments/assets/2447d950-271f-491a-b31a-7e7b0e135a04)
I'm having a problem finding the function 'load_default_simulations', I can't find the function 'load_default_simulations' from apsimNGpy.core.base_data.

**Comment by MAGALA-RICHARD** [comment]
uninstall and try to install from development branch as follows
```python
pip install git+https://github.com/MAGALA-RICHARD/apsimNGpy.git@development

```
