### ISSUE TITLE
 import  error

### ISSUE THREAD

**Issue by lileimax** [MAGALA-RICHARD/apsimNGpy#23]
from apsimNGpy.core.apsim import ApsimModel    error
The detail error was 
KeyError: 'APSIM is not loaded in the system environmental variable'
Can you help me ?

**Comment by MAGALA-RICHARD** [comment]
Most likely you have not added APSIM binaries path to the python Path see the debugging section in the README file

**Comment by lileimax** [comment]
I check the  README file, and added the APSIM path of bin to the python Path 
![46243c62590c6f17af948d5d0bb6ea6](https://github.com/user-attachments/assets/a9d134b5-76e4-435d-86f3-2e13e77520bd)

**Comment by MAGALA-RICHARD** [comment]
the way you are using it is not correct
```python
from apsimNGpy.config import set_apsim_bin_path
apsim_path = 'D:/APSIM/APSIM2024.11.7612/bin/'
set_apsim_bin_path(apsim_path)
```
