### ISSUE TITLE
FIX WORKING WITH NEWER VERSIONS OF APSIMX

### ISSUE THREAD

**Issue by magala-softtech** [MAGALA-RICHARD/apsimNGpy#5]
There was substantial changes to the APSIMX file to allow more command line interface. The API brings errors communicating to the models

**Comment by MAGALA-RICHARD** [comment]
Fixed  new versions are also compatible. The SoilModel is to be deprecated. new versions can call from apsimNGpy.core.apsim import ApsimModel instead of SoilModel class
